<!-- Шаблон для роута admin -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=Config::get('site_name');?></title> <!-- вывел название сайта(ключ 'site_name' в config.php -->
    <link rel="stylesheet" href="/css/style.css"> <!-- подключил свои стили -->
    <script src="/js/admin.js"></script>
    <link rel="icon" href="http://ru.seaicons.com/wp-content/uploads/2016/05/Letter-D-black-icon.png" type="image/x-icon"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-
    Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><?=Config::get('site_name');?> - <?=__('lng.admin', 'Admin Section') ?></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <!-- Скрыл(hide)меню для not authorized users, и добавил (adding) 'logout' link для authorized users.
            Проверка - выполнен ли вход в систему или нет. Если выполнен - показуем существующие пункты меню и 'logout'
             ссылку-->
            <?php if (Session::get('login')){ ?>
            <ul class="nav navbar-nav">
                <!-- добавил класс active для выбранного пункта меню -->
                <li <?php if (App::getRouter()->getController() == 'pages'){ ?>class="active"<?php } ?>><a href="/admin/pages/">Pages</a></li>
                <li <?php if (App::getRouter()->getController() == 'contacts'){ ?>class="active"<?php } ?>><a href="/admin/contacts/">Contact Us</a></li>
                <li><a href="/admin/users/logout">Logout</a></li>
            </ul>
            <?php } ?>
        </div>
    </div>
</nav>

<div class="container">

    <div class="starter-template">
        <!--вызвал ф-ю hasFlash - если метод вернет true то показываем уведомление, тоисть вызываем ф-ю flash-->
        <?php if( Session::hasFlash() ){ ?>
        <div class="alert alert-info" role ="alert">
            <?php Session::flash(); ?>
        </div>
        <?php } ?>
        <!-- Блок с контентом - всё что выводим - значение массива $data по ключу 'content'
        $content = $view_object->render(); из app.class.php -->
        <?=$data['content']?>
    </div>

</div>
<!-- <?=__('lng.test2','default_value')?> -->

</body>
</html>