<!DOCTYPE html>
<html lang="en">
<!-- Главный шаблон (layout) для роута 'default' -->
<head>
    <meta charset="UTF-8">
    <title><?=Config::get('site_name');?></title> <!-- вывел название сайта(ключ 'site_name' в config.php -->
    <link rel="stylesheet" href="/css/style.css"> <!-- подключил свои стили -->
    <link rel="icon" href="http://ru.seaicons.com/wp-content/uploads/2016/05/Letter-D-black-icon.png" type="image/x-icon"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-
    Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><?=Config::get('site_name');?></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <!-- добавил класс active для выбранного пункта меню -->
                <li><a <?php if (App::getRouter()->getController() == 'pages'){ ?>class="active"<?php } ?> href="/pages/">Pages</a></li>
                <li><a <?php if (App::getRouter()->getController() == 'contacts'){ ?>class="active"<?php } ?> href="/contacts/">Contact Us</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">

    <div class="starter-template">
<!--вызываем ф-ю hasFlash если метод вернет true то показываем уведомление, тоисть вызываем ф-ю flash-->
        <?php if( Session::hasFlash() ){ ?>
        <div class="alert alert-info" role ="alert">
            <?php Session::flash(); ?>
        </div>
        <?php } ?>
        <!-- Добавили блок с контентом - всё что нужно вывести - значение массива $data по ключу 'content'
        $content=$view_object->render(); из app.class.php -->
        <?=$data['content']?>
    </div>

</div>
<!--<?=__('lng.test2','default_value')?>-->

</body>
</html>