<!-- HTML Форма для добавления новой страницы. Эта форма точная копия формы редактирования, только разница в том -
в форме добавления отсутствует hidden поля "id" и значений в полях - пустое value.
 -->
<h3>Add page</h3><br />
<form method="post" action="">
    <div class="form-group">
        <label for="alias">Alias</label>
        <input type="text" id="alias" name="alias" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" id="title" name="title" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" id="content" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="is_published">Publish?</label>
        <input type="checkbox" id="is_published" name="is_published" checked="checked" />
    </div>
    <input type="submit" class="btn btn-success" />
</form>