<!-- Представление для метода index.
Выводим  строчку (значения массива $data c ключом)  которую задали в контроллере.
Используем цикл foreach для вывода списка страниц которые содержатся в массиве $data по ключу 'pages'.
Каждая страница в списке выглядит как ссылка на просмотр одной страницы по адресу /pages/view/alias-->
<?php foreach($data['pages'] as $page_data) { ?>
    <div style="margin-top: 20px;">
        <a href="/pages/view/<?=$page_data['alias']?>"><?=$page_data['title']?></a>
    </div>

<?php } ?>