<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Файл формы отправки сообщения -->
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Contact Us:</h3>
<form action = "" method="post"> <!-- пустой атрибут action чтобы форма отправлял. на текущий url и http метод post -->
    <input type="text" class="form-control" placeholder="Your Name" name="name"/><br/>
    <input type="email" class="form-control" placeholder="Your Email" name="email"/><br/>
    <textarea name="messages" class="form-control" placeholder="Your Message"></textarea><br/>
    <button class="btn btn-lg btn-primary btn-block" type="submit" >Send</button>

</form>

</body>
</html>